AC_DEFUN([AC_KLK_CHECKDB],
[
MODULE_CHECKDB_ID="7a1f443e-6840-437c-9bf6-69f813c45282"
AC_SUBST(MODULE_CHECKDB_ID)
MODULE_CHECKDB_NAME="checkdb"
AC_SUBST(MODULE_CHECKDB_NAME)
MODULE_CHECKDB_INTERVAL=10
AC_SUBST(MODULE_CHECKDB_INTERVAL)

dnl Test data
TESTMODULE_CHECKDB_ID=$TESTHELPMODULEPREFIX"checkdb"
AC_SUBST(TESTMODULE_CHECKDB_ID)
])
