AC_DEFUN([AC_KLK_LAUNCHER],
[

APP_LAUNCHER_NAME="launcher"
AC_SUBST(APP_LAUNCHER_NAME)

dnl The test data
APP_LAUNCHER_TEST_ID="testmoduleid"
AC_SUBST(APP_LAUNCHER_TEST_ID)
APP_LAUNCHER_TEST_NAME="testmodulename"
AC_SUBST(APP_LAUNCHER_TEST_NAME)

])
